M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-07-22T09:53:25
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-22T09:53:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,8,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.400
%
G90
G05
T1
X114.315Y-73.22
X182.265Y-73.22
M30
